alias pd="pushd ~/.dotfiles && dtmux"

#Hi3G stuff
alias pdme="pushd ~/kod/mom-engine/"
alias pdma="pushd ~/kod/mom-admin/"
alias pdcf="pushd ~/kod/confirmation/"
alias pdco="pushd ~/kod/checkout/"
alias pdrf="pushd ~/kod/returns-frontend/"
alias pdrb="pushd ~/kod/returns-bff/"
alias pdej="pushd ~/kod/end-to-end-tests/src/test/javascript/"
alias pdsc="pushd ~/kod/bottom-drawer/scmd/"
alias pdcd="pushd ~/kod/cd-kubernetes/"
alias pdlo="pushd ~/vimwiki/tre/"
alias pdlsb="pushd ~/kod/sales-bff-treshop-dk"
alias pdze="pushd ${ZETTELKASTEN_DIR}"

alias npdme="pushd ~/kod/mom-engine/ && dtmux"
alias npdma="pushd ~/kod/mom-admin/ && dtmux"
alias npdcf="pushd ~/kod/confirmation/ && dtmux"
alias npdco="pushd ~/kod/checkout/ && dtmux"
alias npdrf="pushd ~/kod/returns-frontend/ && dtmux"
alias npdrb="pushd ~/kod/returns-bff/ && dtmux"
alias npdej="pushd ~/kod/end-to-end-tests/src/test/javascript/ && dtmux"
alias npdsc="pushd ~/kod/bottom-drawer/scmd/ && dtmux"
alias npdcd="pushd ~/kod/cd-kubernetes/ && dtmux"
alias npdlo="pushd ~/vimwiki/tre/ && dtmux"
alias npdsb="pushd ~/kod/sales-bff-treshop-dk/ && dtmux"

alias ipdme="pushd ~/kod/mom-engine/ && idea . && dtmux"
alias ipdma="pushd ~/kod/mom-admin/  && idea . && dtmux"
alias ipdcf="pushd ~/kod/confirmation/ && idea . && dtmux"
alias ipdco="pushd ~/kod/checkout/ && idea . && dtmux"
alias ipdrf="pushd ~/kod/returns-frontend/ && idea . && dtmux"
alias ipdrb="pushd ~/kod/returns-bff/ && idea . && dtmux"
alias ipdej="pushd ~/kod/end-to-end-tests/src/test/javascript/ && idea . && dtmux"
alias ipdsc="pushd ~/kod/bottom-drawer/scmd/ && idea . && dtmux"
alias ipdcd="pushd ~/kod/cd-kubernetes/ && idea . && dtmux"
alias ipdsb="pushd ~/kod/sales-bff-treshop-dk/ idea . && dtmux"

alias ozi="open ${HOME}/Google\ Drive/_zetinlet"
alias oze="open ${ZETTELKASTEN_DIR}"
